import type { GridCell, GridItem, PurchaseProductId, UserState } from "../../shared/api/gameApi";
import type { CatalogTab, ChainFilter, ContextHint, FlashTone, TierFilter } from "./gameBoard.helpers";

export type GameBoardViewProps = {
  mergeFeedback: {
    cellIndex: number;
    message: string;
    tone: "success" | "new" | "spawn";
    nonce: number;
  } | null;
  isSpawnCelebrating: boolean;
  goalCompletionToast: {
    title: string;
    discoveryLine: string;
    rewardLine: string | null;
  } | null;
  user: UserState;
  flashTone: FlashTone;
  cells: GridCell[];
  targetItem: GridItem | null;
  contextHint: ContextHint;
  selectedCellItem: GridItem | null;
  isHintDismissed: boolean;
  isGuideDismissed: boolean;
  dismissHint: () => void;
  dismissGuide: () => void;
  filledCellsCount: number;
  selectedCell: number | null;
  dragFrom: number | null;
  isMerging: boolean;
  onDropCell: (index: number) => Promise<void>;
  setDragFrom: (index: number | null) => void;
  handleCellClick: (index: number) => Promise<void>;
  getCellTierClassName: (cell: GridCell) => string;
  isSpawning: boolean;
  isClaimingIncome: boolean;
  isUpgradingBase: boolean;
  isDeletingCell: boolean;
  canSpawn: boolean;
  canUpgradeBase: boolean;
  hasSelectedCellItem: boolean;
  canDeleteSelectedCell: boolean;
  selectedCellDeleteCost: number | null;
  spawnItemAction: () => void;
  claimIncomeAction: () => void;
  upgradeBaseAction: () => void;
  deleteCellAction: () => void;
  claimDailyRewardAction: () => void;
  claimAdBoostAction: (
    boostType: "rewarded_free_spawn" | "rewarded_free_delete" | "rewarded_flow_boost" | "rewarded_double_offline_income"
  ) => void;
  purchaseProductAction: (productId: PurchaseProductId) => void;
  isClaimingDailyReward: boolean;
  claimingAdBoostType: "rewarded_free_spawn" | "rewarded_free_delete" | "rewarded_flow_boost" | "rewarded_double_offline_income" | null;
  purchasingProductId: PurchaseProductId | null;
  isCollectionOpen: boolean;
  setIsCollectionOpen: (value: boolean) => void;
  isHelpOpen: boolean;
  setIsHelpOpen: (value: boolean) => void;
  isBonusesOpen: boolean;
  setIsBonusesOpen: (value: boolean) => void;
  isPaymentsInfoOpen: boolean;
  setIsPaymentsInfoOpen: (value: boolean) => void;
  isAuthOpen: boolean;
  setIsAuthOpen: (value: boolean) => void;
  isProfileOpen: boolean;
  setIsProfileOpen: (value: boolean) => void;
  isCatalogOpen: boolean;
  setIsCatalogOpen: (value: boolean) => void;
  isUtilityMenuOpen: boolean;
  setIsUtilityMenuOpen: (value: boolean) => void;
  catalogTab: CatalogTab;
  setCatalogTab: (value: CatalogTab) => void;
  tierFilter: TierFilter;
  setTierFilter: (value: TierFilter) => void;
  chainFilter: ChainFilter;
  setChainFilter: (value: ChainFilter) => void;
  filteredCatalogItems: GridItem[];
  activeRows: number;
};
